// Vivek Patel
class Question7 {
  public static void main(String[] args) {
    String ciphertext = "QHDLXNQLYNGAIGWBCERJFEARNIBKXUSVGZXKYNPXXTKGAATZRQCRFYIDCCLYXHUQXEIXFAFGEAMMALYRGAYXQMTGACDJSYRTLEXUVRVIYFFEGXFKOYSPHGBBYTRESOXUNTXXAKLUAWYDINAAWCZWIFVMCROIUCEIFJYDJAYZJBEOTMUSGAGAYYQNIPTFPYMCBOYDYYSVGWDOJTBZLMFBYJXLQCUDRRIGMIUYWMQUUFRPCZQHTVJOUJSMNRVQQZEJYLACNHRFCPTFENZYEJCLYMBQUCGUMYQDBUAWLQTMOAXCZJBEABHQJYEAMQQDNIRLNTUINRMCYUJAQTZQMGOEXUDEONQPIDBXWNKNIEUNQMBQDUFGXLFXYBVKNTEZCBFJGJUTVHHMBWOZIFQNCTLMBQELYVGNTUHIAXNQUHSROYZJCEFUIACVOBFVAEGBBHGNEIMOHIYRIOZQ";
    
    for (int s = 1; s<= 14; s++){
      int c = 0;
      for (int i = 0; i < ciphertext.length() - 1; i++){
        int shiftedIndex = (i + s) % ciphertext.length();
        if (ciphertext.charAt(i) == ciphertext.charAt(shiftedIndex)){
          c++;
        }
      }
      System.out.println("shift = " + s + ", " + "confidence = " + c);
    }
  }
}